---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```

# Functions

## Clean Data
```{r}
# Define the threshold below which a call is a response call 
threshold <- 100 # 100 is a result from a mixture gaussian model from Frants
# Define max delay (in seconds) for rotation test
delay <- 20

## Function to preprocess the data
CleanData <- function(filename =filename, threshold=threshold){
  
  # Load dataset
  d <- read_delim(filename, "\t") %>% 
  rename( ## More meaningful names to me
    StartTime = Time,
    WhaleID = Source_code,
    WhaleType = Source_type) %>% 
  mutate( # Calculating some additional variables 
    EndTime = StartTime + Duration, 
    Latency = StartTime - l<ag(EndTime, 1),
    DurationPrev = lag(Duration,1),
    CallType = ifelse(Latency < threshold,"ResponseCall","InitiationCall"),
    Age = ifelse(WhaleType == "Juvenile", 1, ifelse(WhaleType == "Indeterminate",2,3))
  )
  

  for (n in c(2:nrow(d))){
    
    if (d$Latency[n] > threshold){
      b <- b + 1 # if the distance from previous call is higher than the threshold, change bout
      }
    d$bout[n] <- b # add bout counter value
  }
  
  ## Remove duplicates due to multiple recording devices
  dups = NULL
  for (i in 2:nrow(d)){
    
    if (d$bout[i]==d$bout[i-1] & d$WhaleID[i]==d$WhaleID[i-1] & d$StartTime[i] - d$StartTime[i-1] < 1 & d$Focal[i]!=d$Focal[i-1]){
      dups <- append(dups,i)
    }
    
  }
  
  if (length(dups)){
    d <- d[-dups,]
  }
  
  d <- d %>% 
  mutate(
    Latency = StartTime - lag(EndTime, 1),
    )
  
  d_Real <- d
  
  for (i in unique(d_Real$bout)){
    ## Let's reset the timer within each bout
    BoutReset <- d_Real$StartTime[d_Real$bout==i][1]
    d_Real$BoutStartTime[d_Real$bout==i] <- d_Real$StartTime[d_Real$bout==i] - BoutReset
    d_Real$BoutEndTime[d_Real$bout==i] <- d_Real$EndTime[d_Real$bout==i] - BoutReset
  }
  
  d_Real <- d_Real %>% mutate(
    BoutLatency = BoutStartTime - lag(BoutEndTime, 1),
  )
  
  d_Real$Type <- "Real"
  
  d_Real$BoutLatency[d_Real$BoutStartTime == 0]<-NA
  
  return(d_Real)
}
```

## Rotation Analysis 
```{r}
RotateData <- function(d = data, threshold = threshold, delay = delay) {

  # We create rotated datasets
  ## for each whale but the first we add a random n of seconds to the timeseries of starting points
  ## we take the shifted timeseries which are now longer than the bout and we cut and paste the sticking out bit to the beginning
    
  for (i in unique(d$bout)){
    
    ## Let's reset the timer within each bout
    BoutReset <- d$StartTime[d$bout==i][1]
    d$BoutStartTime[d$bout==i] <- d$StartTime[d$bout==i] - BoutReset
    d$BoutEndTime[d$bout==i] <- d$EndTime[d$bout==i] - BoutReset
    
    ## identify all callers but the first
    Callers <- unique(d$WhaleID[d$bout==i])
    RotatedCallers <- Callers[-1]
    RotatedDelays <- runif(length(RotatedCallers), min= 1, max= delay)
    
    ## Last call
    LastCall <- nrow(d[d$bout==i,])
    BoutEnd <- d$BoutEndTime[d$bout==i][LastCall]
    
    if (length(Callers)>1){
      
      for (n in seq(length(RotatedCallers))){
        
        rc <- RotatedCallers[n]
        
        d$BoutStartTime[d$bout==i & d$WhaleID == rc] <- d$BoutStartTime[d$bout==i & d$WhaleID == rc] + RotatedDelays[n]
        d$BoutEndTime[d$bout==i & d$WhaleID == rc] <- d$BoutEndTime[d$bout==i & d$WhaleID == rc] + RotatedDelays[n]
        
        d$BoutStartTime[d$bout==i & d$WhaleID == rc & d$BoutStartTime > BoutEnd] <- d$BoutStartTime[d$bout==i & d$WhaleID == rc & d$BoutStartTime > BoutEnd] - BoutEnd
        
        d$BoutEndTime[d$bout==i & d$WhaleID == rc & d$BoutEndTime > BoutEnd] <- d$BoutStartTime[d$bout==i & d$WhaleID == rc & d$BoutEndTime > BoutEnd] + d$Duration[d$bout==i & d$WhaleID == rc & d$BoutEndTime > BoutEnd ]
        
      }
      
    }
    
  }
  
  d <-d[order(d$bout, d$BoutStartTime),]
  
  d <- d %>% mutate(
    BoutLatency = BoutStartTime - lag(BoutEndTime, 1),
  )
   d$BoutLatency[d$BoutStartTime == 0]<-NA
  
  d$Type <- "Rotated"
  
  d <- d[order(d$StartTime),]
  d <- d %>% 
    mutate(
      Latency = StartTime - lag(EndTime, 1),
    )
  
 
  
  return(d)
}
```

## Reset Hypothesis:

```{r}
#Better use of arrange. 
ResetHypothesis2 <- function(data){

  data <- data %>% 
    arrange(Group, CallNr, Onset) %>%
    mutate(Interindividual = 0)
    
  for(i in 2:nrow(data)){
      data[i,"Interindividual"] = ifelse(data$ID[i] == data$ID[i-1], 0, 1) #Check if inter- or intra-timing
  }
  data <- data %>% 
      mutate(Interindividual = as.factor(Interindividual))
  
  #plotting
  plot <- data %>% 
    filter(Latency != "NA") %>%
    ggplot(aes(x = Latency, color = Interindividual)) + geom_density()
  print(plot)
  
  #Testing
  df_Inter <- data %>% 
    filter(Latency != "NA" & Interindividual == 1) 
  
  df_Intra <- data %>%
    filter(Latency != "NA" & Interindividual == 0)
  
  test <- ks.test(df_Inter$Latency, df_Intra$Latency)
  print(test)
  return(data)
}
```

```{r}
### Testing

#Simulate Several Instances of Reset data.
df_list <- list()
for (i in 1:10){
  Start <- Sys.time()
  df_list[[i]] <- ResetModel(n = 100, mu_latency = 150, sd_latency = 15, mu_duration = 300, sd_duration = 100) %>% 
    mutate(Group = i)
  End <- Sys.time()
  print(End - Start)
}
#Bind all simulated data sets together
Reset_Sim <- do.call("rbind", df_list)

ResetHypothesis2(Reset_Sim)

```

## Inhibition Hypothesis


```{r}

#Animal1 = Find specific sequence of Turn-taking communicated by a specific animal (A) in a specific Group (AG).
#Animal2 = Must not be in the same group. As this would be matching whale1 with someone from its original communication. It can be any other Bout either in the #same group or in another group. 
InhibitionHypothesis <- function(df){
  i = 1
  for (g in unique(df$Group)) {
    
    for (id in unique(df$ID[df$Group == g])){
    
      for (b in (unique(df$CallNr[df$Group == g & df$ID == id]))){
        
        #Whale1
        whale1 <- subset(df, Group == g & ID == id & CallNr == b)
        
        if (length(unique(whale1$CallNr))== 1){
          #Whale 2
          whale2_INFO <- df %>% 
            group_by(ID, Group) %>% 
            slice_sample()%>% 
            filter(Group != g & ID != id) %>%
            ungroup() %>% 
            sample_n(1)
        }
        else{
          #Whale 2
          whale2_INFO <- df %>% 
            group_by(ID, Group, CallNr) %>% 
            slice_sample()%>% 
            filter(Group != g & ID != id & CallNr != b) %>%
            ungroup() %>% 
            sample_n(1)
        }
        
        whale2 <- subset(df, Group == whale2_INFO$Group & ID == whale2_INFO$ID & CallNr == whale2_INFO$CallNr)
        
        df_inhib2 <- rbind(whale1,whale2) %>% 
          filter(Latency > 0.1) %>% 
          arrange(Group, CallNr, Onset) %>% 
          mutate(Group = i) %>% 
          mutate(Latency = Onset - lag(Offset, 1))
      
        
      
      #Combine
      if (i == 1) df_inhib_final2 <- df_inhib2
      else df_inhib_final2 <- rbind(df_inhib2, df_inhib_final2)
        
      i = i +1
      }
    } 
  }
  
  #Combine the Shuffled and real data
  df_inhib_final2$Type <-  "Simulated" 
  df$Type <-  "Real"
  
  df_inhib_combined2 <- rbind(df_inhib_final2, df)
  
  #Plot
  Plot_inhib2 <- df_inhib_combined2 %>% 
    ggplot(aes(Latency, color = Type)) + geom_density()
  print(Plot_inhib2)
  #Test
  Test <- ks.test(df_inhib_final2$Latency, df$Latency)
  print(Test)
  
  return(df_inhib_combined2)
}
```


```{r}
### Testing

#There are some issues with sizes of two data frames sometimes not matching... Should be looked at..
df_list_inhib <- list()
for (i in 1:10){
  Start <- Sys.time()
  df_list_inhib[[i]] <- InhibitionModel(n = 100, mu_latency = 150, sd_latency = 15, mu_duration = 300, sd_duration = 100) %>% 
    mutate(Group = i) %>% 
    mutate(ID = ID*i)
  End <- Sys.time()
  print(End - Start)
}


#Bind all simulated data sets together
Inhibition_Sim <- do.call("rbind", df_list_inhib)

#Test
InhibitionHypothesis(Inhibition_Sim)
```


# Coupled Oscillators Hypothesis
To test this, we measured the time interval of marmoset 2’s subsequent calls after each of marmoset 1’s calls.

```{r}
library("readxl")
library(here)
df_Meerkat <- read_excel(here("Data", "Meerkats_demartsev.xlsx"))
names(df_Meerkat) <- gsub(" ", "", names(df_Meerkat))
names(df_Meerkat) <- gsub("#", "", names(df_Meerkat))

```

```{r}
Coupled_Oscilliator_Model<- function(df){
  InterCallsIntervals <- NULL
  for (g in unique(df$Group)){
    for (b in unique(df$CallNr[df$Group == g])){
    
    Caller1 <- df$ID[df$CallNr==b & df$Group == g][1] #Identify the first caller
    Calls1 <- df$Onset[df$CallNr==b & df$ID == Caller1 & df$Group == g] #All Caller1 calls. 
    
    if (length(df$ID[df$CallNr==b & df$ID != Caller1 & df$Group == g]>0)){ #All other calls in that specific Bout and Group not produced by Caller1. 
      
      for (call in Calls1){
        #Intercall timings.
        tempIntervals <- df$Onset[df$CallNr==b & df$ID != Caller1 & df$Group == g] - call
        #Caller Info
        tempCaller <- df$ID[df$CallNr==b & df$ID != Caller1 & df$Group == g] 
        CallNr <- df$CallNr[df$CallNr==b & df$ID != Caller1 & df$Group == g]
        FirstCall <- which(Calls1==call)
        tempData <- data.frame(Intervals = tempIntervals, FirstCaller= Caller1, Caller=tempCaller, CallNr = CallNr, FirstCall=FirstCall, Group = g)
        
        tempData <- subset(tempData, Intervals > 0) #NOTE NOTE NOTE I AM NOT SURE WE SHOULD DO THIS IF WE WANNA LOOK AT CROSS-CORELATION. 
        
        if (exists("InterCallsIntervals")){
          InterCallsIntervals = rbind(InterCallsIntervals,tempData)
          } 
        else {
          InterCallsIntervals = tempData
          }
        }
      }
    }
  }
  
  return(InterCallsIntervals)
}

temp <- Coupled_Oscilliator_Model(df_whale_small)


```

