---
title: "R Notebook"
output: html_notebook
---
# Functions
```{r}
# Define the threshold below which a call is a response call 
threshold <- 100 # 100 is a result from a mixture gaussian model from Frants
# Define max delay (in seconds) for rotation test
delay <- 20

## Function to preprocess the data
CleanData <- function(filename =filename, threshold=threshold){
  
  # Load dataset
  d <- read_delim(filename, "\t") %>% 
  rename( ## More meaningful names to me
    StartTime = Time,
    WhaleID = Source_code,
    WhaleType = Source_type) %>% 
  mutate( # Calculating some additional variables 
    EndTime = StartTime + Duration, 
    Latency = StartTime - l<ag(EndTime, 1),
    DurationPrev = lag(Duration,1),
    CallType = ifelse(Latency < threshold,"ResponseCall","InitiationCall"),
    Age = ifelse(WhaleType == "Juvenile", 1, ifelse(WhaleType == "Indeterminate",2,3))
  )
  

  for (n in c(2:nrow(d))){
    
    if (d$Latency[n] > threshold){
      b <- b + 1 # if the distance from previous call is higher than the threshold, change bout
      }
    d$bout[n] <- b # add bout counter value
  }
  
  ## Remove duplicates due to multiple recording devices
  dups =NULL
  for (i in 2:nrow(d)){
    
    if (d$bout[i]==d$bout[i-1] & d$WhaleID[i]==d$WhaleID[i-1] & d$StartTime[i] - d$StartTime[i-1] < 1 & d$Focal[i]!=d$Focal[i-1]){
      dups <- append(dups,i)
    }
    
  }
  
  if (length(dups)){
    d <- d[-dups,]
  }
  
  d <- d %>% 
  mutate(
    Latency = StartTime - lag(EndTime, 1),
    )
  
  d_Real <- d
  
  for (i in unique(d_Real$bout)){
    ## Let's reset the timer within each bout
    BoutReset <- d_Real$StartTime[d_Real$bout==i][1]
    d_Real$BoutStartTime[d_Real$bout==i] <- d_Real$StartTime[d_Real$bout==i] - BoutReset
    d_Real$BoutEndTime[d_Real$bout==i] <- d_Real$EndTime[d_Real$bout==i] - BoutReset
  }
  
  d_Real <- d_Real %>% mutate(
    BoutLatency = BoutStartTime - lag(BoutEndTime, 1),
  )
  
  d_Real$Type <- "Real"
  
  d_Real$BoutLatency[d_Real$BoutStartTime == 0]<-NA
  
  return(d_Real)
}
```


```{r}
RotateData <- function(d = data, threshold = threshold, delay = delay) {

  # We create rotated datasets
  ## for each whale but the first we add a random n of seconds to the timeseries of starting points
  ## we take the shifted timeseries which are now longer than the bout and we cut and paste the sticking out bit to the beginning
    
  for (i in unique(d$bout)){
    
    ## Let's reset the timer within each bout
    BoutReset <- d$StartTime[d$bout==i][1]
    d$BoutStartTime[d$bout==i] <- d$StartTime[d$bout==i] - BoutReset
    d$BoutEndTime[d$bout==i] <- d$EndTime[d$bout==i] - BoutReset
    
    ## identify all callers but the first
    Callers <- unique(d$WhaleID[d$bout==i])
    RotatedCallers <- Callers[-1]
    RotatedDelays <- runif(length(RotatedCallers), min= 1, max= delay)
    
    ## Last call
    LastCall <- nrow(d[d$bout==i,])
    BoutEnd <- d$BoutEndTime[d$bout==i][LastCall]
    
    if (length(Callers)>1){
      
      for (n in seq(length(RotatedCallers))){
        
        rc <- RotatedCallers[n]
        
        d$BoutStartTime[d$bout==i & d$WhaleID == rc] <- d$BoutStartTime[d$bout==i & d$WhaleID == rc] + RotatedDelays[n]
        d$BoutEndTime[d$bout==i & d$WhaleID == rc] <- d$BoutEndTime[d$bout==i & d$WhaleID == rc] + RotatedDelays[n]
        
        d$BoutStartTime[d$bout==i & d$WhaleID == rc & d$BoutStartTime > BoutEnd] <- d$BoutStartTime[d$bout==i & d$WhaleID == rc & d$BoutStartTime > BoutEnd] - BoutEnd
        
        d$BoutEndTime[d$bout==i & d$WhaleID == rc & d$BoutEndTime > BoutEnd] <- d$BoutStartTime[d$bout==i & d$WhaleID == rc & d$BoutEndTime > BoutEnd] + d$Duration[d$bout==i & d$WhaleID == rc & d$BoutEndTime > BoutEnd ]
        
      }
      
    }
    
  }
  
  d <-d[order(d$bout, d$BoutStartTime),]
  
  d <- d %>% mutate(
    BoutLatency = BoutStartTime - lag(BoutEndTime, 1),
  )
   d$BoutLatency[d$BoutStartTime == 0]<-NA
  
  d$Type <- "Rotated"
  
  d <- d[order(d$StartTime),]
  d <- d %>% 
    mutate(
      Latency = StartTime - lag(EndTime, 1),
    )
  
 
  
  return(d)
}
```

